NVIDIA GPUs found:
GPU 0: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-80648491-6a95-b81d-75b4-052d2dd8c7c9)
GPU 1: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-499f283e-db1e-ee86-a129-055cbe646609)
GPU 2: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-b445d9fd-2ace-3c9e-eb45-3709c4ebad9d)
GPU 3: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-b4192883-e17f-7a02-713d-92e407309931)
GPU 4: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-b8231fe3-7aba-1db3-f672-d401ebc51ebc)
GPU 5: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-66d55b12-e952-3883-7053-ddaf568663bb)
GPU 6: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-0baa35af-3f55-416b-a08c-4be45850e8c6)
GPU 7: NVIDIA GeForce RTX 2080 Ti (UUID: GPU-6e0f49e6-2c17-9b78-08eb-1142a9e648e5)
running python scripts
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 99, in <module>
    evaluate(arguments_strFirst, arguments_strSecond, arguments_strOut)
  File "/ifs/CS/replicated/home/kerdos/cs1470/our-EDSC-pytorch/run.py", line 58, in evaluate
    assert img1.shape == img2.shape
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
finished generating frames in 91
creating gif...
convert-im6.q16: unable to open image `frames/*.png': No such file or directory @ error/blob.c/OpenBlob/2924.
convert-im6.q16: no images defined `output.gif' @ error/convert.c/ConvertImageCommand/3229.
